// Regression coverage for two bugs found while wiring a real module
// (Asteria's feat/module-client-views) that has a table row field typed
// as an array of another named struct (`Vec<PlanetaryPositionWire>` in
// Rust, i.e. `{"Array": {"Ref": N}}` in the describe JSON):
//
// 1. TypeMapper.getEncoderMethod/getDecoderMethod (and therefore every
//    generator that used them directly for a field's whole type) threw
//    `UnsupportedError: No encoder method for type: {Array: {Ref: N}}` —
//    Array types were only handled for U8 (bytes) and, in a couple of
//    generators, for Array<primitive>; Array<Ref<T>> was never handled
//    anywhere.
// 2. Once Array<Ref<T>> support was added, a second bug surfaced: the
//    generated call for a bare Ref-typed field was always `.encode()` /
//    `TypeName.decode()`, but the only generator that ever gives a named
//    Product (struct) type its own file — TableGenerator, whether for a
//    real table, a view's return type, or any other otherwise-uncovered
//    named struct — always emits `encodeBsatn`/`decodeBsatn`, never
//    `encode`/`decode`. Only Sum (enum) types, generated by
//    SumTypeGenerator, actually have plain `encode`/`decode`. So any
//    Ref-typed field pointing at a struct (not an enum) generated code
//    that called a method that didn't exist on the target class.
//
// See test/fixtures/asteria_module_views_describe.README.md for the real
// module this was found against.
//
// 3. A third bug in the same family surfaced once (1) and (2) were fixed:
//    a field typed `Option<SomeMultiFieldStruct>` (a 2-variant Sum whose
//    Some payload is `{"Ref": N}` to an ordinary multi-field struct, e.g.
//    Asteria's `DailySkyWireEnvelope.next_lunar_transition:
//    Option<LunarTransitionWire>`) crashed the same way, even though
//    bare `Ref` fields and `Array<Ref<T>>` fields both worked. The cause
//    was in getOptionInnerType, not in the encode/decode expression
//    builders: it resolved the Some variant's Ref down to its bare
//    structural Product shape before returning it, so by the time
//    getEncodeExpression saw it, the `{"Ref": N}` was already gone and it
//    fell through to the primitive-only getEncoderMethod, throwing.
//    Fixed by having getOptionInnerType return the *unresolved* Ref for
//    this case, so Ref detection downstream still works.
//
// 4. A fourth, unrelated bug surfaced once real Array<Ref<T>> fields
//    started generating: `Array<U8>` (a byte array) was special-cased to
//    `encoder.writeBytes(value)` / `decoder.readBytes()`, but
//    BsatnDecoder.readBytes requires an explicit length argument that
//    nothing on this path reads off the wire first — a real mismatch
//    that would compile but decode wrong (or throw a wrong-arity error,
//    which is how it was actually caught: "1 positional argument
//    expected by 'readBytes', but 0 found"). Fixed by removing the
//    special case entirely; U8 now goes through the same generic
//    per-element writeArray/readArray loop as any other array element
//    type, matching the `List<int>` type toDartType already declares
//    for this shape (toDartType was intentionally left alone rather than
//    also special-cased to Uint8List, to avoid re-diverging the two).
//
// A fifth bug, also found in this pass: TableGenerator's import
// collection only recognized a field whose *entire* type was a bare Ref;
// a Ref reached only via Array<...> or Option<...> (or nested
// combinations) was never imported, so the field's own type compiled
// (per bug 1's fix) but every *use* of the referenced class failed
// "isn't a type" / cascading nullability errors. Fixed by making import
// collection recurse into Array and Option wrappers instead of only
// checking the field's top-level shape.
import 'package:test/test.dart';
import 'package:spacetimedb/src/codegen/models/type_models.dart';
import 'package:spacetimedb/src/codegen/models/table_models.dart';
import 'package:spacetimedb/src/codegen/models/database_schema.dart';
import 'package:spacetimedb/src/codegen/table_generator.dart';
import 'package:spacetimedb/src/codegen/type_mapper.dart';

void main() {
  // A minimal typespace: index 0 is a Product (struct) type, index 1 is a
  // Sum (enum) type, index 2 is a multi-field Product (struct) type with
  // more than one field and no single-field-wrapper/identity shape —
  // enough to distinguish the two generator conventions and to exercise
  // getOptionInnerType's Ref-to-ordinary-multi-field-struct fallback.
  final typeSpace = TypeSpace(types: [
    AlgebraicType(product: ProductType(elements: [])), // 0: struct
    AlgebraicType(sum: SumType(variants: [])), // 1: enum
    AlgebraicType(
      product: ProductType(elements: [
        ProductElement(name: 'kind', algebraicType: {'String': []}),
        ProductElement(name: 'not_before', algebraicType: {'String': []}),
      ]),
    ), // 2: multi-field struct (mirrors LunarTransitionWire's shape)
  ]);
  final typeDefs = [
    TypeDef(scope: [], name: 'PlanetaryPositionWire', typeRef: 0, customOrdering: false),
    TypeDef(scope: [], name: 'SomeEnum', typeRef: 1, customOrdering: false),
    TypeDef(scope: [], name: 'LunarTransitionWire', typeRef: 2, customOrdering: false),
  ];

  group('TypeMapper.getEncodeExpression / getDecodeExpression', () {
    test('primitive type falls back to the plain encoder/decoder method', () {
      expect(
        TypeMapper.getEncodeExpression('value', {'U64': []}),
        'encoder.writeU64(value)',
      );
      expect(
        TypeMapper.getDecodeExpression({'U64': []}),
        'decoder.readU64()',
      );
    });

    test(
        'Array<U8> uses the generic per-element writeArray/readArray loop, '
        'not encoder.writeBytes()/decoder.readBytes() — writeBytes takes no '
        'length but BsatnDecoder.readBytes requires one nothing here reads '
        'off the wire, so a bare writeBytes/readBytes pair would compile '
        'but decode wrong', () {
      expect(
        TypeMapper.getEncodeExpression('value', {
          'Array': {'U8': []}
        }),
        'encoder.writeArray<int>(value, (item) => encoder.writeU8(item))',
      );
      expect(
        TypeMapper.getDecodeExpression({
          'Array': {'U8': []}
        }),
        'decoder.readArray<int>(() => decoder.readU8())',
      );
    });

    test('Array<primitive> generates a writeArray/readArray callback', () {
      expect(
        TypeMapper.getEncodeExpression('value', {
          'Array': {'U64': []}
        }),
        'encoder.writeArray<Int64>(value, (item) => encoder.writeU64(item))',
      );
      expect(
        TypeMapper.getDecodeExpression({
          'Array': {'U64': []}
        }),
        'decoder.readArray<Int64>(() => decoder.readU64())',
      );
    });

    test(
        'a bare Ref to a struct (Product) type calls encodeBsatn/decodeBsatn, '
        'matching what TableGenerator actually emits', () {
      expect(
        TypeMapper.getEncodeExpression(
          'value',
          {'Ref': 0},
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'value.encodeBsatn(encoder)',
      );
      expect(
        TypeMapper.getDecodeExpression(
          {'Ref': 0},
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'PlanetaryPositionWire.decodeBsatn(decoder)',
      );
    });

    test(
        'a bare Ref to an enum (Sum) type calls plain encode/decode, matching '
        'what SumTypeGenerator actually emits', () {
      expect(
        TypeMapper.getEncodeExpression(
          'value',
          {'Ref': 1},
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'value.encode(encoder)',
      );
      expect(
        TypeMapper.getDecodeExpression(
          {'Ref': 1},
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'SomeEnum.decode(decoder)',
      );
    });

    test(
        'Array<Ref<StructType>> (the exact shape that used to throw '
        '"No encoder method for type: {Array: {Ref: 0}}") encodes/decodes '
        'each element via encodeBsatn/decodeBsatn', () {
      final arrayOfRefStruct = {
        'Array': {'Ref': 0}
      };

      expect(
        TypeMapper.getEncodeExpression(
          'value',
          arrayOfRefStruct,
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'encoder.writeArray<PlanetaryPositionWire>(value, (item) => item.encodeBsatn(encoder))',
      );
      expect(
        TypeMapper.getDecodeExpression(
          arrayOfRefStruct,
          typeSpace: typeSpace,
          typeDefs: typeDefs,
        ),
        'decoder.readArray<PlanetaryPositionWire>(() => PlanetaryPositionWire.decodeBsatn(decoder))',
      );
    });
  });

  group('TypeMapper.getOptionInnerType — Ref to an ordinary struct', () {
    // The raw JSON shape of `Option<LunarTransitionWire>`: a 2-variant Sum
    // where one variant is unit-like (None) and the other's algebraic_type
    // is a bare Ref (Some), exactly as `spacetime describe --json` emits
    // it for a Rust `Option<SomeStruct>` field.
    final optionOfRefStruct = {
      'Sum': {
        'variants': [
          {
            'name': {'some': 'none'},
            'algebraic_type': <String, dynamic>{},
          },
          {
            'name': {'some': 'some'},
            'algebraic_type': {'Ref': 2},
          },
        ],
      },
    };

    test('returns the unresolved Ref, not its resolved structural shape',
        () {
      final inner = TypeMapper.getOptionInnerType(
        optionOfRefStruct,
        typeSpace: typeSpace,
        typeDefs: typeDefs,
      );

      expect(inner, {'Ref': 2},
          reason: 'resolving the Ref here strips the information '
              'getEncodeExpression/getDecodeExpression need to pick '
              'encodeBsatn/decodeBsatn over the primitive-only fallback');
    });

    test(
        'end-to-end: an Option<Ref<struct>> field encodes/decodes via '
        'writeOption/readOption calling encodeBsatn/decodeBsatn, not a '
        'crash on the bare resolved Product', () {
      final inner = TypeMapper.getOptionInnerType(
        optionOfRefStruct,
        typeSpace: typeSpace,
        typeDefs: typeDefs,
      )!;

      final encodeExpr = TypeMapper.getEncodeExpression(
        'v',
        inner,
        typeSpace: typeSpace,
        typeDefs: typeDefs,
      );
      final decodeExpr = TypeMapper.getDecodeExpression(
        inner,
        typeSpace: typeSpace,
        typeDefs: typeDefs,
      );

      expect(encodeExpr, 'v.encodeBsatn(encoder)');
      expect(decodeExpr, 'LunarTransitionWire.decodeBsatn(decoder)');
    });
  });

  group('TableGenerator — imports for Ref reached via Array/Option', () {
    test(
        'a table with an Array<Ref<T>> field and an Option<Ref<T>> field '
        'imports both referenced types, not just a bare-Ref field', () {
      // typespace: 0 = the table row itself, 1 = LunarTransitionWire
      // (multi-field struct, reused from the group above), 2 = another
      // multi-field struct used only via Array<Ref<2>>.
      final rowType = AlgebraicType(
        product: ProductType(elements: [
          ProductElement(
            name: 'transitions',
            algebraicType: {
              'Array': {'Ref': 2}
            },
          ),
          ProductElement(
            name: 'next_transition',
            algebraicType: {
              'Sum': {
                'variants': [
                  {'name': null, 'algebraic_type': <String, dynamic>{}},
                  {
                    'name': {'some': 'some'},
                    'algebraic_type': {'Ref': 1},
                  },
                ],
              },
            },
          ),
        ]),
      );

      final rowTypeSpace = TypeSpace(types: [
        rowType,
        typeSpace.types[2], // LunarTransitionWire, from the group above
        AlgebraicType(
          product: ProductType(elements: [
            ProductElement(name: 'foo', algebraicType: {'String': []}),
            ProductElement(name: 'bar', algebraicType: {'String': []}),
          ]),
        ),
      ]);
      final rowTypeDefs = [
        TypeDef(scope: [], name: 'SomeRow', typeRef: 0, customOrdering: false),
        TypeDef(scope: [], name: 'LunarTransitionWire', typeRef: 1, customOrdering: false),
        TypeDef(scope: [], name: 'OtherWire', typeRef: 2, customOrdering: false),
      ];

      final schema = DatabaseSchema(
        databaseName: 'test-db',
        typeSpace: rowTypeSpace,
        tables: const [],
        reducers: const [],
        types: rowTypeDefs,
        views: const [],
      );
      final table = TableSchema(
        name: 'some_row',
        productTypeRef: 0,
        primaryKey: const [],
        indexes: const [],
        constraints: const [],
        sequences: const [],
        schedule: const {},
        tableType: const {},
        tableAccess: const {},
      );

      final generated = TableGenerator(schema, table).generate();

      expect(generated, contains("import 'other_wire.dart';"),
          reason: 'Array<Ref<OtherWire>> field must import OtherWire');
      expect(generated, contains("import 'lunar_transition_wire.dart';"),
          reason: 'Option<Ref<LunarTransitionWire>> field must import it');
    });
  });
}
